#!/usr/bin/env python

from approval_processorMPutils import *
from sys import stdin

alert = str(stdin.read())
alert = json.loads(alert)
f = open('lvalerts.txt', 'a')
f.write('{0}\n\n'.format(alert))
f.close()

parseAlert(alert)
